repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.6.5
    hooks:
      # Fix imports
      - id: ruff
        args: ["--fix", "--select", "I"]
      # Linter (with fix)
      - id: ruff
        args: ["--fix"]
      # Formatter
      - id: ruff-format
        types_or: ["python"]
